// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wizarddata.Data;

namespace wizarddata.Migrations
{
    [DbContext(typeof(WizardContext))]
    [Migration("20200411004955_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("wizarddata.Data.Competency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Competencies");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Competency");
                });

            modelBuilder.Entity("wizarddata.Data.CompetencyDisposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompetencyId")
                        .HasColumnType("int");

                    b.Property<int?>("DispositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("DispositionId");

                    b.ToTable("CompetencyDispositions");
                });

            modelBuilder.Entity("wizarddata.Data.Disposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Discipline")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Dispositions");
                });

            modelBuilder.Entity("wizarddata.Data.KSPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AtomicCompetencyId")
                        .HasColumnType("int");

                    b.Property<int?>("KnowledgeElementId")
                        .HasColumnType("int");

                    b.Property<int?>("SkillLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtomicCompetencyId");

                    b.HasIndex("KnowledgeElementId");

                    b.HasIndex("SkillLevelId");

                    b.ToTable("KSPairs");
                });

            modelBuilder.Entity("wizarddata.Data.KnowledgeElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartesianIndex")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Etymology")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SemioticIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeElements");
                });

            modelBuilder.Entity("wizarddata.Data.SkillLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartesianIndex")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("SkillLevels");
                });

            modelBuilder.Entity("wizarddata.Data.AtomicCompetency", b =>
                {
                    b.HasBaseType("wizarddata.Data.Competency");

                    b.HasDiscriminator().HasValue("AtomicCompetency");
                });

            modelBuilder.Entity("wizarddata.Data.CompetencyDisposition", b =>
                {
                    b.HasOne("wizarddata.Data.Competency", "Competency")
                        .WithMany("CompetencyDispostions")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wizarddata.Data.Disposition", "Disposition")
                        .WithMany()
                        .HasForeignKey("DispositionId");
                });

            modelBuilder.Entity("wizarddata.Data.KSPair", b =>
                {
                    b.HasOne("wizarddata.Data.AtomicCompetency", "AtomicCompetency")
                        .WithMany("KSPairs")
                        .HasForeignKey("AtomicCompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wizarddata.Data.KnowledgeElement", "KnowledgeElement")
                        .WithMany()
                        .HasForeignKey("KnowledgeElementId");

                    b.HasOne("wizarddata.Data.SkillLevel", "SkillLevel")
                        .WithMany()
                        .HasForeignKey("SkillLevelId");
                });
#pragma warning restore 612, 618
        }
    }
}
